# Generated by Django 4.1.2 on 2024-03-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='contact_icons')),
                ('type', models.CharField(blank=True, choices=[('Email', 'Email'), ('Phone', 'Phone'), ('Address', 'Address')], max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
