# Generated by Django 4.1.2 on 2024-03-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='brands'),
        ),
    ]
