# Generated by Django 4.1.2 on 2024-03-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_brand_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
