# Generated by Django 4.1.2 on 2024-03-15 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_cake_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='img',
        ),
        migrations.CreateModel(
            name='CakeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='cakes')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cake.cake')),
            ],
        ),
    ]
