# Generated by Django 4.1.2 on 2024-03-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0004_remove_cake_img_cakeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='cakes')),
            ],
        ),
        migrations.DeleteModel(
            name='CakeImage',
        ),
        migrations.AddField(
            model_name='cake',
            name='images',
            field=models.ManyToManyField(blank=True, to='cake.image'),
        ),
    ]
