# Generated by Django 4.1.2 on 2024-03-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0006_brand_address_brand_created_at_brand_near_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
