# Generated by Django 4.1.2 on 2024-03-15 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0008_category_color_cake_composition_cake_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='colors',
        ),
        migrations.AddField(
            model_name='cake',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cake.color'),
        ),
    ]
