# Generated by Django 4.1.2 on 2024-03-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0010_brandsocialmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandsocialmedia',
            name='name',
        ),
        migrations.AddField(
            model_name='brandsocialmedia',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='brands'),
        ),
    ]
