# Generated by Django 4.1.2 on 2024-03-15 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0012_socialmedia_delete_brandsocialmedia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='social_media',
            new_name='social_medias',
        ),
    ]
