# Generated by Django 4.1.2 on 2024-03-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0013_rename_social_media_brand_social_medias'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
